export const ITINERARY_MAIN_FIELD_LABELS = [
  'Voy No.',
  'Next Port & Dock Name',
  'UTC Offset',
  'Purpose',
  'B/F or I/F Qty (MT/BBLS)',
  'ETA (LT)',
  'ETB (LT)',
  '預計L/D rate (MT/h)',
  'ETC (LT)',
  'ETD (LT)',
  'Arr Draft',
  'Dep Draft',
  'Arr ROB',
  'Dep ROB',
] as const;

export const ITINERARY_PARAMETER_FIELD_LABELS = [
  'DTG(NM)',
  '預估航速(kn)',
  '剩餘航行時間(h)',
  '預估等待時間(靠泊前)(h)',
  '預計航道航行時間(h)',
  '作業艙號',
  '裝卸貨量(MT)',
  '預計L/D rate (MT/h)',
  '預計作業時間(h)',
  '預估等待/延誤時間(完貨前)(h)',
  '預估等待/延誤時間(完貨後)(h)',
] as const;
